apiVersion: v1
kind: Service
metadata:
  name: svc-nodejs
  labels:
    app: bk-nodejs
spec:
  type: LoadBalancer
  selector:
    app: bk-nodejs
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
