apiVersion: v1
kind: Service
metadata:
  name: svc-neo4j
  labels:
    app: bk-neo4j
spec:
  type: LoadBalancer
  selector:
    app: bk-neo4j
  ports:
  - port: 80
    targetPort: 7474
    protocol: TCP
